---
title: Flappy Astronaut
hero_image: images/banner.png
description: Make a Flappy Bird clone using your Raspberry Pi and the Sense HAT
original_url: https://raspberrypi.org/learning/flappy-astronaut
theme: green
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: space, games
technologies: python
site_areas: ''
steps:
- title: Introduction
- title: What you will need
- title: Flappy Astronaut
- title: Representing pixels
- title: Using 2D lists with the Sense HAT
- title: Generating pipes
- title: Mind the gaps
- title: Create a function to make more pipes
- title: Moving pipes algorithm
- title: Moving the pipes
- title: Watching the pipes move
- title: Adding your astronaut
- title: Moving the astronaut
- title: Edge detection
- title: Collisions
- title: Finishing your game
- title: "Challenge: taking it further"
